# Uncomment the next line to define a global platform for your project
source  'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'testFireBase' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
use_modular_headers!

  # Pods for testFireBase
# Add the Firebase pod for Google Analytics

#分析，talkingdata ?
#pod 'FirebaseAnalytics'
#pod 'FirebaseCrashlytics'
#pod 'Firebase/Crashlytics'
#crash崩溃
pod 'FirebaseCrashlytics'

#性能
pod 'FirebasePerformance'

#埋点
pod 'FirebaseAnalytics'


# For Analytics without IDFA collection capability, use this pod instead
# pod ‘Firebase/AnalyticsWithoutAdIdSupport’

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
#pod 'FirebaseAuth'
#pod 'FirebaseFirestore'

end
