# Uncomment the next line to define a global platform for your project
source  'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'testFireBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#use_modular_headers!

  # Pods for testFireBase
# Add the Firebase pod for Google Analytics
#pod 'FirebaseAnalytics'
#pod 'FirebaseCrashlytics'
#pod 'Firebase/Crashlytics'
pod 'FirebaseCrashlytics'

# For Analytics without IDFA collection capability, use this pod instead
# pod ‘Firebase/AnalyticsWithoutAdIdSupport’

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
#pod 'FirebaseAuth'
#pod 'FirebaseFirestore'

end
